apiVersion: v2
name: vinbot-rides-frontend
description: A Helm chart for VinBot Rides Frontend Application
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - frontend
  - angular
  - vinbot-rides
home: https://dev.vinbotride.vinayakshukla.me
sources:
  - https://github.com/imvinayakshukla/VinaBot-Rides
maintainers:
  - name: Vinayak Shukla
    email: vinayak@vinayakshukla.me
